// Generated by gencpp from file jetbot_msgs/SetValue.msg
// DO NOT EDIT!


#ifndef JETBOT_MSGS_MESSAGE_SETVALUE_H
#define JETBOT_MSGS_MESSAGE_SETVALUE_H

#include <ros/service_traits.h>


#include <jetbot_msgs/SetValueRequest.h>
#include <jetbot_msgs/SetValueResponse.h>


namespace jetbot_msgs
{

struct SetValue
{

typedef SetValueRequest Request;
typedef SetValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetValue
} // namespace jetbot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetbot_msgs::SetValue > {
  static const char* value()
  {
    return "0aca93dcf6d857f0e5a0dc6be1eaa9fb";
  }

  static const char* value(const ::jetbot_msgs::SetValue&) { return value(); }
};

template<>
struct DataType< ::jetbot_msgs::SetValue > {
  static const char* value()
  {
    return "jetbot_msgs/SetValue";
  }

  static const char* value(const ::jetbot_msgs::SetValue&) { return value(); }
};


// service_traits::MD5Sum< ::jetbot_msgs::SetValueRequest> should match
// service_traits::MD5Sum< ::jetbot_msgs::SetValue >
template<>
struct MD5Sum< ::jetbot_msgs::SetValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetbot_msgs::SetValue >::value();
  }
  static const char* value(const ::jetbot_msgs::SetValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbot_msgs::SetValueRequest> should match
// service_traits::DataType< ::jetbot_msgs::SetValue >
template<>
struct DataType< ::jetbot_msgs::SetValueRequest>
{
  static const char* value()
  {
    return DataType< ::jetbot_msgs::SetValue >::value();
  }
  static const char* value(const ::jetbot_msgs::SetValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetbot_msgs::SetValueResponse> should match
// service_traits::MD5Sum< ::jetbot_msgs::SetValue >
template<>
struct MD5Sum< ::jetbot_msgs::SetValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetbot_msgs::SetValue >::value();
  }
  static const char* value(const ::jetbot_msgs::SetValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbot_msgs::SetValueResponse> should match
// service_traits::DataType< ::jetbot_msgs::SetValue >
template<>
struct DataType< ::jetbot_msgs::SetValueResponse>
{
  static const char* value()
  {
    return DataType< ::jetbot_msgs::SetValue >::value();
  }
  static const char* value(const ::jetbot_msgs::SetValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETBOT_MSGS_MESSAGE_SETVALUE_H
